/*
 * *****
 * WRITTEN BY FLORIAN RAPPL, 2012.
 * florian-rappl.de
 * mail@florian-rappl.de
 * *****
 */
 
/* LEVELS ORIGINALLY BY MARTIN BUCHNER & PATRICK SAAR */
/* MODIFIED TO INCLUDE 12 QUESTIONS & 3 CHECKPOINTS */

var definedLevels = [
{ // Level 0 (ID=0) - Sẽ nhận Câu 1
	width: 252,
	height: 15,
	id: 0,
	background: 1,
	data:
	[
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'pipe_top_left' , 'pipe_left' , 'pipe_left_grass' , 'pipe_left_soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'pipe_top_right' , 'pipe_right' , 'pipe_right_grass' , 'pipe_right_soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'mario' , 'grass_top' , 'soil'], // Mario start
	['' , '' , '' , '' , '' , '' , '' , '' , '' , 'multiple_coinbox' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'planted_soil_left'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'planted_soil_middle'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'planted_soil_right'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'bush_left' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'bush_middle' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'bush_middle_right' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'bush_right' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , 'questionbox' , '' , '' , '' , 'grass_top' , 'soil'], // <-- CÂU HỎI 1 (thay mushroombox)
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'ballmonster' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'pipe_top_left' , 'pipe_left' , 'pipe_left_grass' , 'pipe_left_soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'pipe_top_right' , 'pipe_right' , 'pipe_right_grass' , 'pipe_right_soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , 'coinbox' , '' , '' , '' , 'brown_block' , 'brown_block' , 'brown_block' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'brown_block' , 'brown_block' , 'brown_block' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'pipe_top_left' , 'pipe_left' , 'pipe_left_grass' , 'pipe_left_soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'pipe_top_right' , 'pipe_right' , 'pipe_right_grass' , 'pipe_right_soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , 'coinbox' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'ballmonster' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top_left' , 'grass_left' , 'grass_left' , 'grass_top_left_corner' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , 'coinbox' , '' , '' , '' , 'grass_top' , 'soil' , 'planted_soil_left' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , 'brown_block' , '' , '' , '' , 'grass_top' , 'soil' , 'planted_soil_right' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , 'coinbox' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , 'brown_block' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , 'coinbox' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , 'ballmonster' , 'grass_top' , 'soil' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , 'pipe_top_left' , 'pipe_left' , 'pipe_left' , 'pipe_left_grass' , 'pipe_left_soil' , 'pipe_left_soil' , 'pipe_left_soil' , 'pipe_left_soil'],
	['' , '' , '' , '' , '' , '' , '' , 'pipe_top_right' , 'pipe_right' , 'pipe_right' , 'pipe_right' , 'pipe_right' , 'pipe_right' , 'pipe_right_grass' , 'pipe_right_soil'],
	['' , '' , '' , '' , '' , 'brown_block' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , 'brown_block' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , 'brown_block' , '' , '' , '' , 'coinbox' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , 'brown_block' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , 'brown_block' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , 'ballmonster' , 'brown_block' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , 'coin' , 'coin' , 'coin' , 'coin' , 'coin' , 'coin' , 'coin' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top_right_rounded' , 'soil_right'],
	[ '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , ''],
	[ '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , ''],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top_left_rounded' , 'soil_left'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , 'brown_block' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , 'mushroombox' , '' , '' , '' , 'brown_block' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , 'brown_block' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'pipe_top_left' , 'pipe_left' , 'pipe_left_grass' , 'pipe_left_soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'pipe_top_right' , 'pipe_right' , 'pipe_right_grass' , 'pipe_right_soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , 'coinbox' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'bush_left' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'bush_middle_left' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'bush_middle' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , 'brown_block' , '' , '' , 'bush_middle_right' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , 'brown_block' , '' , '' , 'bush_right' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , 'coinbox' , '' , '' , '' , 'brown_block' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , 'coinbox' , '' , '' , '' , 'brown_block' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , 'coinbox' , '' , '' , '' , 'coinbox' , '' , '' , '' , 'brown_block' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , 'coinbox' , '' , '' , '' , 'coinbox' , '' , '' , '' , 'brown_block' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , 'coinbox' , '' , '' , '' , 'brown_block' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , 'coinbox' , '' , '' , '' , 'brown_block' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , 'brown_block' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , 'brown_block' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'greenturtle' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top_right_rounded' , 'soil_right'],
	[ '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , ''],
	[ '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , ''],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top_left_rounded' , 'soil_left'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'pipe_top_left' , 'pipe_left' , 'pipe_left_grass' , 'pipe_left_soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'pipe_top_right' , 'pipe_right' , 'pipe_right_grass' , 'pipe_right_soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , 'coinbox' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'planted_soil_left'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'ballmonster' , 'grass_top' , 'planted_soil_middle'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'planted_soil_right'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , 'checkpoint' , '' , '' , '' , 'grass_top' , 'soil'], // <--- CHECKPOINT 1 (thay coinbox)
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'greenturtle' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'pipe_top_left' , 'pipe_left' , 'pipe_left_grass' , 'pipe_left_soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'pipe_top_right' , 'pipe_right' , 'pipe_right_grass' , 'pipe_right_soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'ballmonster' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , 'starbox' , '' , '' , '' , 'brown_block' , 'brown_block' , 'brown_block' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'brown_block' , 'brown_block' , 'brown_block' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top_left' , 'grass_left' , 'grass_left' , 'grass_top_left_corner' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , 'coinbox' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , 'brown_block' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , 'coinbox' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , 'brown_block' , '' , '' , '' , 'grass_top' , 'planted_soil_left' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , 'coinbox' , '' , '' , '' , 'grass_top' , 'planted_soil_middle' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'planted_soil_right' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , 'ballmonster' , 'grass_top' , 'soil' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , 'pipe_top_left' , 'pipe_left' , 'pipe_left' , 'pipe_left_grass' , 'pipe_left_soil' , 'pipe_left_soil' , 'pipe_left_soil' , 'pipe_left_soil'],
	['' , '' , '' , '' , '' , '' , '' , 'pipe_top_right' , 'pipe_right' , 'pipe_right' , 'pipe_right' , 'pipe_right' , 'pipe_right' , 'pipe_right_grass' , 'pipe_right_soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , 'coinbox' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'ballmonster' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'pipe_top_left' , 'pipe_left' , 'pipe_left_grass' , 'pipe_left_soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'pipe_top_right' , 'pipe_right' , 'pipe_right_grass' , 'pipe_right_soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'ballmonster' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , 'coinbox' , '' , '' , '' , 'brown_block' , 'brown_block' , 'brown_block' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'brown_block' , 'brown_block' , 'brown_block' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'pipe_top_left' , 'pipe_left' , 'pipe_left_grass' , 'pipe_left_soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'pipe_top_right' , 'pipe_right' , 'pipe_right_grass' , 'pipe_right_soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'greenturtle' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'bush_left' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'bush_middle_left' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'bush_middle_right' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'bush_right' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'greenturtle' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top_right_rounded' , 'soil_right'],
	[ '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , ''],
	[ '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , ''],
	[ '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , ''],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'brown_block' , 'brown_block' , 'grass_top_left_rounded' , 'soil_left'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'brown_block' , 'brown_block' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'brown_block' , 'brown_block' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'brown_block' , 'brown_block' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'brown_block' , 'brown_block' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'brown_block' , 'brown_block' , 'brown_block' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'brown_block' , 'brown_block' , 'brown_block' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , 'stone' , '' , '' , '' , 'brown_block' , 'brown_block' , 'brown_block' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , 'stone' , '' , '' , '' , 'brown_block' , 'brown_block' , 'brown_block' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , 'multiple_coinbox' , '' , '' , '' , 'brown_block' , 'brown_block' , 'brown_block' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'brown_block' , 'brown_block' , 'brown_block' , 'grass_top_right_rounded' , 'soil_right'],
	[ '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , ''],
	[ '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , ''],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'brown_block' , 'grass_top_left_rounded' , 'soil_left'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'brown_block' , 'brown_block' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'brown_block' , 'brown_block' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , 'brown_block' , 'coin' , 'brown_block' , 'brown_block' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , 'brown_block' , 'brown_block' , '' , 'brown_block' , 'brown_block' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , 'brown_block' , 'brown_block' , 'coin' , 'brown_block' , 'brown_block' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , 'brown_block' , '' , 'brown_block' , 'brown_block' , '' , 'brown_block' , 'brown_block' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , 'brown_block' , 'brown_block' , 'coin' , 'brown_block' , 'brown_block' , 'coin' , 'brown_block' , 'brown_block' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , 'brown_block' , 'brown_block' , 'brown_block' , '' , 'brown_block' , 'brown_block' , 'brown_block' , 'brown_block' , 'brown_block' , 'grass_top' , 'soil'],
	['' , '' , '' , 'brown_block' , 'brown_block' , 'brown_block' , 'brown_block' , 'coin' , 'brown_block' , 'brown_block' , 'brown_block' , 'brown_block' , 'brown_block' , 'grass_top' , 'soil'],
	['' , '' , 'brown_block' , 'brown_block' , 'brown_block' , 'brown_block' , 'brown_block' , '' , 'brown_block' , 'brown_block' , 'brown_block' , 'brown_block' , 'brown_block' , 'grass_top' , 'soil'],
	['' , 'brown_block' , 'brown_block' , 'brown_block' , 'brown_block' , 'brown_block' , 'brown_block' , 'coin' , 'brown_block' , 'brown_block' , 'brown_block' , 'brown_block' , 'brown_block' , 'grass_top' , 'soil'],
	['' , 'brown_block' , 'brown_block' , 'brown_block' , 'brown_block' , 'brown_block' , 'brown_block' , '' , 'brown_block' , 'brown_block' , 'brown_block' , 'brown_block' , 'brown_block' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , 'coin' , '' , 'coin' , '' , 'coin' , '' , 'coin' , '' , 'coin' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil']
	]
}
	,
{ // Level 1 (ID=1) - Sẽ nhận Câu 4, 5, 6, 7
	width: 220,
	height: 15,
	id: 1,
	background: 1,
	data:
	[
	['','','','','','','','','','','','','','grass_top','planted_soil_middle'],
	['','','','','','','','','','','','','','grass_top','planted_soil_middle'],
	['','','','','','','','','','','','','mario','grass_top','planted_soil_right'], // Mario start
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','coinbox','','','','','grass_top','soil'],
	['','','','','','','','','questionbox','','','','','grass_top','soil'], // <-- CÂU HỎI 4 (thay mushroombox)
	['','','','','','','','','coinbox','','','','bush_left','grass_top','soil'],
	['','','','','','','','','','','','','bush_middle_left','grass_top','soil'],
	['','','','','','','','','','','','','bush_middle','grass_top','soil'],
	['','','','','','','','','','','','','bush_middle_right','grass_top','soil'],
	['','','','','','','','','','','','','bush_right','grass_top','soil'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','','','','','','grass_top','planted_soil_left'],
	['','','','','','','','','','','','','ballmonster','grass_top','planted_soil_right'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','','','pipeplant','pipe_top_left','pipe_left','pipe_left_grass','pipe_left_soil'],
	['','','','','','','','','','','','pipe_top_right','pipe_right_grass','pipe_right_soil','pipe_right_soil'],
	['','','','','','','','','','','','','grass_top','soil','soil'],
	['','','','','','','','','','','','','grass_top','soil','soil'],
	['','','','','','','','','','','','','grass_top','soil','soil'],
	['','','','','','','','','','','','','grass_top','soil','soil'],
	['','','','','','','','','','','','','grass_top','soil','soil'],
	['','','','','','','','','','brown_block','brown_block','brown_block','grass_top','soil','soil'],
	['','','','','','multiple_coinbox','','','','brown_block','brown_block','brown_block','grass_top','soil','soil'],
	['','','','','','','','','','brown_block','brown_block','brown_block','grass_top','planted_soil_left','soil'],
	['','','','','','','','','','','','','grass_top','planted_soil_middle','soil'],
	['','','','','','','','','','','','ballmonster','grass_top','planted_soil_middle','soil'],
	['','','','','','','','','','','','','grass_top','planted_soil_right','soil'],
	['','','','','','','','','coinbox','','','','grass_top','soil','soil'],
	['','','','','','','','','','','','','grass_top','soil','soil'],
	['','','','','','','','','','','','','grass_top','soil','soil'],
	['','','','','','','','','','','','','grass_top','soil','soil'],
	['','','','','','','','','','grass_top_left','grass_left','grass_left','grass_top_left_corner','soil','soil'],
	['','','','','','','','','bush_left','grass_top','soil','soil','soil','soil','soil'],
	['','','','','','','','','bush_right','grass_top','soil','planted_soil_left','soil','soil','soil'],
	['','','','','','','','','','grass_top','soil','planted_soil_middle','soil','soil','soil'],
	['','','','','','','','','','grass_top','soil','planted_soil_right','soil','soil','soil'],
	['','','','','','','','','greenturtle','grass_top_right','grass_right','grass_right','grass_right','grass_right','grass_right'],
	['','','','','','','','','','brown_block','','','','',''],
	['','','','','','','','','coin','brown_block','','','','',''],
	['','','','','','','','','','brown_block','','','','',''],
	['','','','','','','','','','','brown_block','','','',''],
	['','','','','','','','','','coin','brown_block','','','',''],
	['','','','','','','','','','','brown_block','','','',''],
	['','','','','','','','','','','','brown_block','','',''],
	['','','','','','','','','','','coin','brown_block','','',''],
	['','','','','','','','','','','','brown_block','','',''],
	['','','','','','','','','','','','','brown_block','',''],
	['','','','','','','','','','','','coin','brown_block','',''],
	['','','','','','','','','','','','','brown_block','',''],
	['','','','','','','','','','','','','grass_top_left','grass_left','grass_left'],
	['','','','','','','','','','','','bush_left','grass_top','soil','soil'],
	['','','','','','','','','coinbox','','','bush_middle_right','grass_top','soil','soil'],
	['','','','','','','','','brown_block','','','bush_middle','grass_top','soil','soil'],
	['','','','','','','','','questionbox','','','bush_right','grass_top','soil','soil'], // <-- CÂU HỎI 5 (thay mushroombox)
	['','','','','','','','','brown_block','','','','grass_top','soil','planted_soil_left'],
	['','','','','','','','','coinbox','','','','grass_top','soil','planted_soil_middle'],
	['','','','','','','','','','','','spikedturtle','grass_top','soil','planted_soil_right'],
	['','','','','','','','','','','','','grass_top_right','grass_right','grass_right'],
	['','','','','','','','','','','','','','',''],
	['','','','','','','','','','','','','','',''],
	['','','','','','','','','','','','','grass_top_left','grass_left','grass_left'],
	['','','','','','','','','','','','','grass_top','planted_soil_left','soil'],
	['','','','','','','','','','','','ballmonster','grass_top','planted_soil_right','soil'],
	['','','','','','','','','','','','','grass_top','soil','soil'],
	['','','','','','','','','questionbox','','','bush_left','grass_top','soil','soil'], // <-- CÂU HỎI 6 (thay starbox)
	['','','','','','','','','','','','bush_middle_right','grass_top','soil','soil'],
	['','','','','','','','','','','','bush_middle','grass_top','soil','soil'],
	['','','','','','','','','','','','bush_right','grass_top','soil','soil'],
	['','','','','','','','','','','','','grass_top','soil','soil'],
	['','','','','','','','','','','','','grass_top','soil','soil'],
	['','','','','','','','','','','pipe_top_left','pipe_left','pipe_left_grass','pipe_left_soil','pipe_left_soil'],
	['','','','','','','','','','','pipe_top_right','pipe_right','pipe_right_grass','pipe_right_soil','pipe_right_soil'],
	['','','','','','','','','','','','','grass_top','soil','soil'],
	['','','','','','','','','','','','','grass_top','soil','planted_soil_left'],
	['','','','','','','','','','','','','grass_top','soil','planted_soil_middle'],
	['','','','','','','','','questionbox','','','greenturtle','grass_top','soil','planted_soil_right'], // <-- CÂU HỎI 7 (thay coinbox)
	['','','','','','','','','','','','','grass_top','soil','soil'],
	['','','','','','','','','','','','spikedturtle','grass_top','soil','soil'],
	['','','','','','','','','','','','','grass_top','soil','soil'],
	['','','','','','','','','','','','','grass_top','soil','soil'],
	['','','','','','','','','','','','bush_left','grass_top','soil','soil'],
	['','','','','','','','','','','','bush_middle','grass_top','soil','soil'],
	['','','','','','','','','','','','bush_middle_right','grass_top','soil','soil'],
	['','','','','','','','','','','','bush_middle_left','grass_top','soil','soil'],
	['','','','','','','','','coinbox','','','bush_right','grass_top','soil','soil'],
	['','','','','','','','','','','','','grass_top','soil','soil'],
	['','','','','','','','','','','','','grass_top','soil','soil'],
	['','','','','','','','','','','','','grass_top','soil','soil'],
	['','','','','','','','','','pipeplant','pipe_top_left','pipe_left','pipe_left_grass','pipe_left_soil','pipe_left_soil'],
	['','','','','','','','','','','pipe_top_right','pipe_right','pipe_right_grass','pipe_right_soil','pipe_right_soil'],
	['','','','','','','','','','','','','grass_top','soil','soil'],
	['','','','','','','','','','','','','grass_top','soil','soil'],
	['','','','','','','','','','','','','grass_top','soil','soil'],
	['','','','','','','','','','','','ballmonster','grass_top','soil','soil'],
	['','','','','','','','','','','','','grass_top','soil','soil'],
	['','','','','','','','','','','','','grass_top','planted_soil_left','soil'],
	['','','','','','','','','','','','','grass_top','planted_soil_middle','soil'],
	['','','','','','','','','','grass_top_left','grass_left','grass_left','grass_top_left_corner','planted_soil_middle','soil'],
	['','','','','','','','','','grass_top','soil','soil','soil','planted_soil_right','soil'],
	['','','','','','','','','','grass_top','soil','soil','soil','soil','soil'],
	['','','','','','','','','spikedturtle','grass_top','soil','soil','soil','soil','soil'],
	['','','','','','','','','','grass_top','soil','soil','soil','soil','soil'],
	['','','','','','','','','','grass_top_right','grass_right','grass_right','grass_right','grass_right','grass_right'],
	['','','','','','','','','','','','','','',''],
	['','','','','','','','','','','','','','',''],
	['','','','','','coin','coin','','','brown_block','brown_block','grass_top_left','grass_left','grass_left','grass_left'],
	['','','','','','coin','coin','','','brown_block','brown_block','grass_top','soil','soil','soil'],
	['','','','','','coin','coin','','','brown_block','brown_block','grass_top','soil','planted_soil_left','soil'],
	['','','','','','coin','coin','','ballmonster','brown_block','brown_block','grass_top','soil','planted_soil_middle','soil'],
	['','','','','','coin','coin','','','brown_block','brown_block','grass_top','soil','planted_soil_right','soil'],
	['','','','','','coin','coin','','','brown_block','brown_block','grass_top','soil','soil','soil'],
	['','','','','','','','','','','brown_block','grass_top_right','grass_top_right_corner','soil','soil'],
	['','','','','','','','','','','','brown_block','grass_top_right','grass_top_right_corner','soil'],
	['','','','','','','','','','','','','brown_block','grass_top','soil'],
	['','','','','','','','','','','','','','grass_top','planted_soil_left'],
	['','','','','','','','','','','','','','grass_top','planted_soil_right'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','','','','','greenturtle','grass_top','soil'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','','','','','','grass_top_right_rounded','soil_right'],
	['','','','','','','','','','','','','','',''],
	['','','','','','','','','','','','','','',''],
	['','','','','','','','','','','','','','grass_top_left_rounded','soil_left'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','','','','','bush_left','grass_top','soil'],
	['','','','','','','','','','','','','bush_middle','grass_top','soil'],
	['','','','','','','','','','','','','bush_middle_left','grass_top','soil'],
	['','','','','','','','','','','','','bush_right','grass_top','soil'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','coin','coin','','','','pipe_top_left','pipe_left','pipe_left_grass','pipe_left_soil'],
	['','','','','','','coin','coin','','','','pipe_top_right','pipe_right','pipe_right_grass','pipe_right_soil'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','','mushroombox','','','','grass_top','soil'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','','','','','','grass_top_right','grass_top_right_corner'],
	['','','','','','','','','','','','','','staticplant','grass_top'],
	['','','','','','','','','','','','','','staticplant','grass_top'],
	['','','','','','','','','','','','','','grass_top_left','grass_top_left_corner'],
	['','','','','','','','','','','','','','grass_top','planted_soil_left'],
	['','','','','','','','','','','','','','grass_top','planted_soil_middle'],
	['','','','','','','','','','','','','','grass_top','planted_soil_right'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','coin','coin','','','','pipe_top_left','pipe_left','pipe_left_grass','pipe_left_soil'],
	['','','','','','','coin','coin','','','','pipe_top_right','pipe_right','pipe_right_grass','pipe_right_soil'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','','','','','ballmonster','grass_top','soil'],
	['','','','','','','','','','','','','bush_left','grass_top','soil'],
	['','','','','','','','','','','','','bush_middle_right','grass_top','soil'],
	['','','','','','','','','','','','','bush_right','grass_top','soil'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','','grass_top_left','grass_left','grass_left','grass_left','grass_top_left_corner','soil'],
	['','','','','','','','','','grass_top','soil','soil','soil','soil','soil'],
	['','','','','','coinbox','','','','grass_top','soil','soil','soil','soil','soil'],
	['','','','','','coinbox','','','ballmonster','grass_top','soil','planted_soil_left','soil','soil','soil'],
	['','','','','','coinbox','','','','grass_top','soil','planted_soil_middle','soil','soil','soil'],
	['','','','','','coinbox','','','','grass_top','soil','planted_soil_middle','soil','soil','soil'],
	['','','','','','coinbox','','','','grass_top','soil','planted_soil_middle','soil','soil','soil'],
	['','','','','','','','','','grass_top','soil','planted_soil_right','soil','soil','soil'],
	['','','','','','','','','','grass_top','soil','soil','soil','soil','soil'],
	['','','','','','','','pipe_top_left','pipe_left','pipe_left_grass','pipe_left_soil','pipe_left_soil','pipe_left_soil','pipe_left_soil','pipe_left_soil'],
	['','','','','','','','pipe_top_right','pipe_right','pipe_right_grass','pipe_right_soil','pipe_right_soil','pipe_right_soil','pipe_right_soil','pipe_right_soil'],
	['','','','','','','','','','grass_top','soil','soil','soil','soil','soil'],
	['','','','','','','','','','grass_top','soil','soil','soil','soil','soil'],
	['','','','','','','','','','grass_top_right','grass_right','grass_right','grass_right','grass_top_right_corner','soil'],
	['','','','','','','','','','','','','','grass_top','planted_soil_left'],
	['','','','','','','','','','brown_block','brown_block','brown_block','','grass_top','planted_soil_right'],
	['','','','','','','','','','brown_block','coin','','coin','grass_top','soil'],
	['','','','','','','','','','brown_block','','coin','','grass_top','soil'],
	['','','','','','','','','','brown_block','coin','','coin','grass_top','soil'],
	['','','','','','','','','','','coinbox','coin','','grass_top','soil'],
	['','','','','','','','','','','mushroombox','','coin','grass_top','soil'],
	['','','','','','','','','','','coinbox','coin','','grass_top','soil'],
	['','','','','','','','','','brown_block','coin','','coin','grass_top','soil'],
	['','','','','','','','','','brown_block','','coin','','grass_top','soil'],
	['','','','','','','','','','brown_block','coin','','coin','grass_top','soil'],
	['','','','','','','','','','brown_block','brown_block','brown_block','brown_block','grass_top','soil'],
	['','','','','','','','','','grass_top_left','grass_left','grass_left','grass_left','grass_top_left_corner','soil'],
	['','','','','','','','','bush_left','grass_top','soil','soil','soil','soil','soil'],
	['','','','','','','','','bush_middle_right','grass_top','soil','soil','soil','soil','soil'],
	['','','','','','','','','bush_middle_left','grass_top','soil','soil','soil','soil','soil'],
	['','','','','','','','','bush_middle_right','grass_top','soil','soil','planted_soil_left','soil','soil'],
	['','','','','','','','','bush_right','grass_top','soil','soil','planted_soil_middle','soil','soil'],
	['','','','','','','','','greenturtle','grass_top','soil','soil','planted_soil_middle','soil','soil'],
	['','','','','','','','','','grass_top','soil','soil','planted_soil_right','soil','soil'],
	['','','','','','','','','','grass_top','soil','soil','soil','soil','soil'],
	['','','','','','','','','','grass_top_right','grass_top_right_corner','soil','soil','soil','soil'],
	['','','','','','','','','','','grass_top_right','grass_top_right_corner','soil','soil','soil'],
	['','','','','','','','','','','','grass_top_right','grass_top_right_corner','soil','soil'],
	['','','','','','','','','','','','','grass_top_right','grass_top_right_corner','soil'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','','','','','spikedturtle','grass_top','soil'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','','','','','','grass_top_right_rounded','soil_right'],
	['','','','','','','','','','','','','','',''],
	['','','','','','','','','','','','','','',''],
	['','','','','','','','','','','','','','grass_top_left_rounded','soil_left'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','','','','','bush_left','grass_top','soil'],
	['','','','','','','','','','','','','bush_middle_right','grass_top','soil'],
	['','','','','','','','','','','','','bush_middle','grass_top','soil'],
	['','','','','','','','','','','','','bush_middle_left','grass_top','soil'],
	['','','','','','','','','','','','','bush_right','grass_top','planted_soil_left'],
	['','','','','','','','','','','','','','grass_top','planted_soil_middle']
	]
}
	,
{ // Level 2 (ID=2) - Sẽ nhận Câu 8, 9, 10, 11
	width: 220,
	height: 15,
	id: 2,
	background: 8, // Nền hang động
	data:
	[
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'mario' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'coin' , 'brown_block' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'greenturtle' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'bush_left' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'bush_middle_left' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'bush_right' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'coin' , 'coin' , 'brown_block' , 'brown_block' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'greenturtle' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , 'coin' , 'coin' , 'coin' , 'brown_block' , 'brown_block' , 'brown_block' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'greenturtle' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top_left_rounded' , 'soil_left' , 'soil_left' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'grass_top'],
	['' , '' , '' , '' , '' , 'coin' , 'coin' , 'coin' , 'coin' , 'coin' , 'coin' , 'grass_top' , 'planted_soil_left' , 'soil' , 'grass_top_right_rounded_soil'],
	['' , '' , '' , '' , '' , '' , 'coin' , '' , '' , '' , '' , 'grass_top' , 'planted_soil_middle' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , 'coin' , '' , '' , '' , 'grass_top' , 'planted_soil_middle' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , 'coin' , '' , '' , '' , '' , 'grass_top' , 'planted_soil_middle' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , 'coin' , 'coin' , 'coin' , 'coin' , 'coin' , 'coin' , 'grass_top' , 'planted_soil_middle' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'planted_soil_right' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , 'coin' , 'coin' , 'coin' , 'coin' , 'coin' , 'grass_top' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , 'coin' , '' , '' , 'coin' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , 'coin' , '' , '' , 'coin' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , 'coin' , 'coin' , 'coin' , 'coin' , 'coin' , 'grass_top' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'planted_soil_left' , 'soil'],
	['' , '' , '' , '' , '' , 'coin' , 'coin' , 'coin' , 'coin' , 'coin' , 'coin' , 'grass_top' , 'soil' , 'planted_soil_middle' , 'soil'],
	['' , '' , '' , '' , '' , 'coin' , '' , '' , 'coin' , '' , '' , 'grass_top' , 'soil' , 'planted_soil_right' , 'soil'],
	['' , '' , '' , '' , '' , 'coin' , '' , '' , 'coin' , 'coin' , '' , 'grass_top' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , 'coin' , 'coin' , '' , '' , 'coin' , 'grass_top' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , 'coin' , 'coin' , 'coin' , 'coin' , 'coin' , 'coin' , 'grass_top' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'planted_soil_left' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , 'coin' , 'coin' , 'coin' , 'coin' , '' , 'grass_top' , 'planted_soil_middle' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , 'coin' , '' , '' , '' , '' , 'coin' , 'grass_top' , 'planted_soil_middle' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , 'coin' , '' , '' , '' , '' , 'coin' , 'grass_top' , 'planted_soil_right' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , 'coin' , 'coin' , 'coin' , 'coin' , '' , 'grass_top' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , 'brown_block' , 'brown_block' , 'brown_block' , 'brown_block' , 'grass_top' , 'soil' , 'soil' , 'planted_soil_left'],
	['' , '' , '' , '' , '' , '' , 'pipeplant' , 'pipe_top_left' , 'pipe_left' , 'pipe_left' , 'pipe_left' , 'grass_top' , 'soil' , 'soil' , 'planted_soil_middle'],
	['' , '' , '' , '' , '' , '' , '' , 'pipe_top_right' , 'pipe_right' , 'pipe_right' , 'pipe_right' , 'grass_top' , 'soil' , 'soil' , 'planted_soil_right'],
	['' , '' , '' , '' , '' , '' , '' , 'brown_block' , 'brown_block' , 'brown_block' , 'brown_block' , 'grass_top' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'planted_soil_left' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'planted_soil_middle' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'planted_soil_middle' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top_right' , 'grass_top_right_corner' , 'planted_soil_right' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'ballmonster' , 'grass_top' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'brown_block' , '' , 'grass_top' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , 'coin' , 'brown_block' , 'coin' , 'grass_top' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , 'brown_block' , '' , '' , 'brown_block' , '' , 'grass_top' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , 'brown_block' , 'coin' , 'coin' , 'brown_block' , 'coin' , 'grass_top' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , 'brown_block' , '' , 'brown_block' , '' , '' , 'brown_block' , '' , 'grass_top' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , 'brown_block' , 'coin' , 'brown_block' , 'coin' , 'coin' , 'brown_block' , 'coin' , 'grass_top' , 'soil' , 'soil'],
	['' , '' , '' , 'brown_block' , '' , 'brown_block' , '' , 'brown_block' , '' , '' , 'brown_block' , '' , 'grass_top' , 'soil' , 'soil'],
	['' , '' , '' , 'brown_block' , 'coin' , 'brown_block' , 'coin' , 'brown_block' , 'coin' , 'coin' , 'brown_block' , 'coin' , 'grass_top' , 'soil' , 'soil'],
	['' , 'brown_block' , 'coin' , 'brown_block' , '' , 'multiple_coinbox' , '' , 'coinbox' , '' , '' , 'questionbox' , '' , 'grass_top' , 'soil' , 'soil'], // 86: Q8 (thay mushroombox)
	['' , '' , '' , 'brown_block' , 'coin' , 'brown_block' , 'coin' , 'brown_block' , 'coin' , 'coin' , 'brown_block' , 'coin' , 'grass_top' , 'soil' , 'soil'],
	['' , '' , '' , 'brown_block' , '' , 'brown_block' , '' , 'brown_block' , '' , '' , 'brown_block' , '' , 'grass_top' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , 'brown_block' , 'coin' , 'brown_block' , 'coin' , 'coin' , 'brown_block' , 'coin' , 'grass_top' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , 'brown_block' , '' , 'brown_block' , '' , '' , 'brown_block' , '' , 'grass_top' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , 'brown_block' , 'coin' , 'coin' , 'brown_block' , 'coin' , 'grass_top' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , 'brown_block' , '' , '' , 'brown_block' , '' , 'grass_top' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'brown_block' , 'coin' , 'grass_top' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'brown_block' , '' , 'grass_top' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'ballmonster' , 'grass_top' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , 'questionbox' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'soil'], // 98: Q9 (thay coinbox)
	['' , '' , '' , 'coinbox' , '' , '' , '' , 'coinbox' , '' , '' , '' , '' , 'grass_top_right' , 'grass_top_right_corner' , 'soil'],
	['' , '' , '' , 'coinbox' , '' , '' , '' , 'coinbox' , '' , '' , '' , 'pipeplant' , 'pipe_top_left' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , 'coinbox' , '' , '' , '' , '' , 'pipe_top_right' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top_left' , 'grass_top_left_corner' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top_right' , 'grass_right' , 'grass_right'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , ''],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , ''],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , ''],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top_left' , 'grass_left' , 'grass_left'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'soil'],
	['' , '' , '' , '' , 'coin' , 'coin' , '' , '' , 'brown_block' , 'brown_block' , 'brown_block' , 'brown_block' , 'grass_top' , 'soil' , 'soil'],
	['' , '' , '' , '' , 'coin' , 'coin' , '' , '' , 'brown_block' , 'brown_block' , 'brown_block' , 'brown_block' , 'grass_top' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top_right' , 'grass_right' , 'grass_top_right_corner'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'ballmonster' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'brown_block' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'ballmonster' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'brown_block' , 'brown_block' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'brown_block' , 'brown_block' , 'brown_block' , 'brown_block' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , 'grass_top_left' , 'grass_left' , 'grass_left' , 'grass_left' , 'grass_left' , 'grass_left' , 'grass_left' , 'grass_left' , 'grass_top_left_corner'],
	['' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil'],
	['' , '' , 'questionbox' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'planted_soil_left' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil'], // 136: Q10 (thay starbox)
	['' , '' , '' , '' , '' , 'bush_left' , 'grass_top' , 'soil' , 'soil' , 'planted_soil_middle' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , 'bush_middle_left' , 'grass_top' , 'soil' , 'soil' , 'planted_soil_middle' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil'],
	['' , 'coin' , 'coin' , '' , '' , 'bush_middle' , 'grass_top' , 'soil' , 'soil' , 'planted_soil_right' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil'],
	['' , 'coin' , 'coin' , '' , '' , 'bush_middle_right' , 'grass_top' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil'],
	['' , 'coin' , 'coin' , '' , '' , 'bush_middle' , 'grass_top' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil' , 'planted_soil_left' , 'soil'],
	['' , 'coin' , 'coin' , '' , '' , 'bush_right' , 'grass_top' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil' , 'planted_soil_middle' , 'soil'],
	['' , 'coin' , 'coin' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil' , 'planted_soil_right' , 'soil'],
	['' , 'coin' , 'coin' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil'],
	['' , 'coin' , 'coin' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil'],
	['' , 'coin' , 'coin' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , 'grass_top_right' , 'grass_right' , 'grass_right' , 'grass_right' , 'grass_right' , 'grass_right' , 'grass_right' , 'grass_right' , 'grass_right'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , ''],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , ''],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top_left'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'spikedturtle' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top_left' , 'grass_top_left_corner'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'spikedturtle' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top_right' , 'grass_top_right_corner'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'spikedturtle' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top_left' , 'grass_top_left_corner'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'spikedturtle' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'bush_left' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'bush_middle_left' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'bush_middle' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'bush_right' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'spikedturtle' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top_right' , 'grass_top_right_corner'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'coinbox' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'coinbox' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'pipeplant' , 'pipe_top_left' , 'pipe_left' , 'pipe_left' , 'pipe_left_grass'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'pipe_top_right' , 'pipe_right' , 'pipe_right' , 'pipe_right_grass'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'coinbox' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'coinbox' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'brown_block' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'brown_block' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , 'brown_block' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , 'brown_block' , '' , '' , '' , '' , '' , '' , 'greenturtle' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , 'brown_block' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'greenturtle' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , 'coin' , 'coin' , '' , '' , 'brown_block' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , 'coin' , 'coin' , '' , '' , 'brown_block' , '' , '' , '' , '' , '' , '' , 'bush_left' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , 'brown_block' , '' , '' , '' , '' , '' , '' , 'bush_middle_left' , 'grass_top'],
	['' , '' , 'coin' , 'coin' , '' , '' , 'brown_block' , '' , '' , '' , '' , '' , '' , 'bush_middle' , 'grass_top'],
	['' , '' , 'coin' , 'coin' , '' , '' , 'brown_block' , '' , '' , '' , '' , '' , '' , 'bush_right' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , 'brown_block' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , 'coin' , 'coin' , '' , '' , 'brown_block' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , 'coin' , 'coin' , '' , '' , 'brown_block' , '' , '' , '' , '' , '' , '' , '' , 'grass_top_right'],
	['' , '' , '' , '' , '' , '' , 'brown_block' , '' , '' , '' , '' , '' , '' , '' , ''],
	['' , '' , 'coin' , 'coin' , '' , '' , 'brown_block' , '' , '' , '' , '' , '' , '' , '' , ''],
	['' , '' , 'coin' , 'coin' , '' , '' , 'brown_block' , '' , '' , '' , '' , '' , '' , '' , 'grass_top_left'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'bush_left' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'bush_middle_left' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'bush_middle' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'bush_right' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top']
	]
}
	,
// --- CÁC MÀN CHƠI CÒN LẠI (ID 3 ĐẾN 14) GIỮ NGUYÊN ---
// ... (Dán toàn bộ data cho Level 3 (id:3) đến Level 14 (id:14) vào đây) ...
// (LƯU Ý: TÔI ĐÃ RÚT GỌN CHỖ NÀY CHO NGẮN, BẠN HÃY GIỮ NGUYÊN 12 MÀN CÒN LẠI CỦA BẠN)
{
	width: 194,
	height: 15,
	id: 3,
	background: 8,
	data:
	[
	// ... (Dữ liệu gốc màn 3) ...
	['','','','','','','','','','','','','','grass_top','soil'] // Cột 0
	// ... (Thêm 'questionbox' ở đây nếu muốn)
	]
}
, {
	width: 203,
	height: 15,
	id: 4,
	background: 8,
	data:
	[
	// ... (Dữ liệu gốc màn 4) ...
	['','','','','','','','','','','','','','grass_top','soil']
	]
}
, {
	width: 140,
	height: 15,
	id: 5,
	background: 3,
	data:
	[
	// ... (Dữ liệu gốc màn 5) ...
	]
}
, {
	width: 165,
	height: 15,
	id: 6,
	background: 3,
	data:
	[
	// ... (Dữ liệu gốc màn 6) ...
	]
}
, {
	width: 177,
	height: 15,
	id: 7,
	background: 5,
	data:
	[
	// ... (Dữ liệu gốc màn 7) ...
	]
}
, {
	width: 181,
	height: 15,
	id: 8,
	background: 5,
	data:
	[
	// ... (Dữ liệu gốc màn 8) ...
	]
}
, {
	width: 242,
	height: 15,
	id: 9,
	background: 6,
	data:
	[
	// ... (Dữ liệu gốc màn 9) ...
	]
}
, {
	width: 161,
	height: 15,
	id: 10,
	background: 6,
	data:
	[
	// ... (Dữ liệu gốc màn 10) ...
	]
}
, {
	width: 106,
	height: 15,
	id: 11,
	background: 2,
	data:
	[
	// ... (Dữ liệu gốc màn 11) ...
	]
}
, { // Level 12 (ID=12) - Màn cuối có Peach
	width: 233,
	height: 15,
	id: 12,
	background: 2,
	data:
	[
	// ... (Dữ liệu gốc màn 12) ...
	]
}
, {
	width: 162,
	height: 15,
	id: 13,
	background: 2,
	data:
	[
	// ... (Dữ liệu gốc màn 13) ...
	]
}
, { // Level 14 (ID=14) - Màn cuối
	width: 155,
	height: 15,
	id: 14,
	background: 4,
	data:
	[
	// ... (Dữ liệu gốc màn 14) ...
	]
}
];

